# Put your application specific error code into this file instead of status.yml
# This file will be merge into the status.yml during the server startup.
# Please allocate the range for the application error codes within your organization
# to ensure no reused for an error code across the organization for tracing.

# 20000-29999 common error codes within your business domain.
# It is highly recommended to have common error codes shared within your organization
# or your line of business and put them into the externalized status.yml file.

# 30000-99999 customize error code that cannot be found in common range.
# Only use this section if you cannot make your error code into 20000-29999 range on time.
# In this case, the error code defined here will be merged to the status.yml during startup.
# To ensure there is no reuse of error code, this application will use the range 30000-31000.
ERR30000:
  statusCode: 400
  code: ERR30000
  message: ERROR_IN_APP
  description: This is  the  error in this example application.

ERR30001:
  statusCode: 500
  code: ERR30001
  message: Database process error
  description: The DB process has error.

ERR30002:
  statusCode: 422
  code: ERR30002
  message: Data cannot find error
  description: Cannot find data by the request.

ERR30003:
  statusCode: 422
  code: ERR30003
  message: campsite is not available
  description: Error on the reservation, campsite is noy available for the input period. Follow dates have been booked.

ERR30004:
  statusCode: 400
  code: ERR30004
  message: Cannot get resevation by Id
  description: Error on getting reservation, Cannot get resevation by Id.

ERR30005:
  statusCode: 400
  code: ERR30005
  message: Cannot update resevation
  description: Error on updating reservation, Cannot update resevation.